// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis. // <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DevAdventCalendarCompetition.Repository.Migrations
{
    public partial class TestManyAnswers : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_TestAnswer_Test_TestId",
                table: "TestAnswer");

            migrationBuilder.DropForeignKey(
                name: "FK_TestAnswer_AspNetUsers_UserId",
                table: "TestAnswer");

            migrationBuilder.DropTable(
                name: "WrongAnswer");

            migrationBuilder.DropPrimaryKey(
                name: "PK_TestAnswer",
                table: "TestAnswer");

            migrationBuilder.DropIndex(
                name: "IX_TestAnswer_TestId",
                table: "TestAnswer");

            migrationBuilder.DropIndex(
                name: "IX_TestAnswer_UserId",
                table: "TestAnswer");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Test",
                table: "Test");

            migrationBuilder.DropColumn(
                name: "FirstName",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "SecondName",
                table: "AspNetUsers");

            migrationBuilder.DropColumn(
                name: "AnsweringTime",
                table: "TestAnswer");

            migrationBuilder.DropColumn(
                name: "AnsweringTimeOffset",
                table: "TestAnswer");

            migrationBuilder.DropColumn(
                name: "UserId",
                table: "TestAnswer");

            migrationBuilder.DropColumn(
                name: "HashedAnswer",
                table: "Test");

            migrationBuilder.DropColumn(
                name: "PlainAnswer",
                table: "Test");

            migrationBuilder.RenameTable(
                name: "TestAnswer",
                newName: "TestAnswers");

            migrationBuilder.RenameTable(
                name: "Test",
                newName: "Tests");

            migrationBuilder.AddColumn<string>(
                name: "Answer",
                table: "TestAnswers",
                nullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_TestAnswers",
                table: "TestAnswers",
                columns: new[] { "TestId", "Id" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_Tests",
                table: "Tests",
                column: "Id");

            migrationBuilder.CreateTable(
                name: "TestCorrectAnswers",
                columns: table => new
                {
                    TestId = table.Column<int>(nullable: false),
                    UserId = table.Column<string>(nullable: false),
                    Id = table.Column<int>(nullable: false),
                    AnsweringTime = table.Column<DateTime>(nullable: false),
                    AnsweringTimeOffset = table.Column<TimeSpan>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TestCorrectAnswers", x => new { x.Id });
                    table.ForeignKey(
                        name: "FK_TestCorrectAnswers_Tests_TestId",
                        column: x => x.TestId,
                        principalTable: "Tests",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_TestCorrectAnswers_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "TestWrongAnswers",
                columns: table => new
                {
                    TestId = table.Column<int>(nullable: false),
                    UserId = table.Column<string>(nullable: false),
                    Id = table.Column<int>(nullable: false),
                    Time = table.Column<DateTime>(nullable: false),
                    Answer = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TestWrongAnswers", x => new { x.Id });
                    table.ForeignKey(
                        name: "FK_TestWrongAnswers_Tests_TestId",
                        column: x => x.TestId,
                        principalTable: "Tests",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_TestWrongAnswers_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_TestCorrectAnswers_UserId",
                table: "TestCorrectAnswers",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_TestWrongAnswers_UserId",
                table: "TestWrongAnswers",
                column: "UserId");

            migrationBuilder.AddForeignKey(
                name: "FK_TestAnswers_Tests_TestId",
                table: "TestAnswers",
                column: "TestId",
                principalTable: "Tests",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_TestAnswers_Tests_TestId",
                table: "TestAnswers");

            migrationBuilder.DropTable(
                name: "TestCorrectAnswers");

            migrationBuilder.DropTable(
                name: "TestWrongAnswers");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Tests",
                table: "Tests");

            migrationBuilder.DropPrimaryKey(
                name: "PK_TestAnswers",
                table: "TestAnswers");

            migrationBuilder.DropColumn(
                name: "Answer",
                table: "TestAnswers");

            migrationBuilder.RenameTable(
                name: "Tests",
                newName: "Test");

            migrationBuilder.RenameTable(
                name: "TestAnswers",
                newName: "TestAnswer");

            migrationBuilder.AddColumn<string>(
                name: "FirstName",
                table: "AspNetUsers",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "SecondName",
                table: "AspNetUsers",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "HashedAnswer",
                table: "Test",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "PlainAnswer",
                table: "Test",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "AnsweringTime",
                table: "TestAnswer",
                type: "datetime2",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<TimeSpan>(
                name: "AnsweringTimeOffset",
                table: "TestAnswer",
                type: "time",
                nullable: false,
                defaultValue: new TimeSpan(0, 0, 0, 0, 0));

            migrationBuilder.AddColumn<string>(
                name: "UserId",
                table: "TestAnswer",
                type: "nvarchar(450)",
                maxLength: 450,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Test",
                table: "Test",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_TestAnswer",
                table: "TestAnswer",
                column: "Id");

            migrationBuilder.CreateTable(
                name: "WrongAnswer",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Answer = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TestId = table.Column<int>(type: "int", nullable: false),
                    Time = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UserId = table.Column<string>(type: "nvarchar(450)", maxLength: 450, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_WrongAnswer", x => x.Id);
                    table.ForeignKey(
                        name: "FK_WrongAnswer_Test_TestId",
                        column: x => x.TestId,
                        principalTable: "Test",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_WrongAnswer_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_TestAnswer_TestId",
                table: "TestAnswer",
                column: "TestId");

            migrationBuilder.CreateIndex(
                name: "IX_TestAnswer_UserId",
                table: "TestAnswer",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_WrongAnswer_TestId",
                table: "WrongAnswer",
                column: "TestId");

            migrationBuilder.CreateIndex(
                name: "IX_WrongAnswer_UserId",
                table: "WrongAnswer",
                column: "UserId");

            migrationBuilder.AddForeignKey(
                name: "FK_TestAnswer_Test_TestId",
                table: "TestAnswer",
                column: "TestId",
                principalTable: "Test",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_TestAnswer_AspNetUsers_UserId",
                table: "TestAnswer",
                column: "UserId",
                principalTable: "AspNetUsers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
